image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar ./artifacts/app-ibank-build-for-testers.jar &
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable

build_script:
  - ./gradlew test --info
